CREATE SCHEMA IF NOT EXISTS Revelex DEFAULT CHARACTER SET latin1;

USE Revelex;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(80) NOT NULL,
  firstname VARCHAR(80) NOT NULL,
  lastname VARCHAR(80) NOT NULL,
  birth_date DATE NOT NULL,  
  password CHAR(250) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX (email)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;